# Keep release-25.11 up-to-date with changes from upstream and thoughtfull branches.
#
# Difference from upstream should be only thoughtfull branches:
# https://github.com/nix-community/home-manager/compare/release-25.11...thoughtfull-nix:home-manager:release-25.11
name: Update release-25.11
on:
  push:
    branches:
      - workflows
  schedule:
    # every day at midnight EST/EDT
    - cron: "0 4,5 * * *"
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  update:
    defaults:
      run:
        shell: bash
    name: Update release-25.11
    runs-on: ubuntu-latest
    steps:
      # Workaround lack of timezone support in Github Action crons
      # https://github.com/orgs/community/discussions/13454#discussioncomment-11159669
      - name: Check if it's midnight
        run: |
          current_hour=$(TZ='America/New_York' date +'%H')
          echo "Current hour in EST/EDT: $current_hour"

          if [[ "${{github.event_name}}" != "schedule" || "$current_hour" == "00" ]]; then
            echo "It's midnight EST/EDT (or not)! Running tasks..."
            echo "run_steps=true" >> $GITHUB_ENV
          else
            echo "It's not midnight EST/EDT! Skipping tasks."
          fi
      - name: Checkout repository
        if: env.run_steps == 'true'
        uses: thoughtfull-systems/checkout-then-configure@main
        with:
          ref: release-25.11
          fetch-depth: 0
          # Upstream occasionally changes workflows and to pull those changes we need `workflows`
          # write permission which is not possible with the default Github token
          token: ${{secrets.PAT}}
      - name: Add upstream remote
        if: env.run_steps == 'true'
        run: |
          git remote add -t release-25.11 --no-tags -f upstream "https://github.com/nix-community/home-manager.git"
      - name: Merge from upstream
        if: env.run_steps == 'true'
        run: |
          git merge --no-ff upstream/release-25.11
      - name: Merge thoughtfull branches
        if: env.run_steps == 'true'
        run: |
          git merge --no-ff origin/workflows
      - name: Push to origin
        if: env.run_steps == 'true'
        run: |
          git push origin release-25.11
